from enum import Enum


class Mode(str, Enum):
    OBJECT = "OBJECT"
    EDIT = "EDIT"
    POSE = "POSE"
    SCULPT = "SCULPT"
    VERTEX_PAINT = "VERTEX_PAINT"
    WEIGHT_PAINT = "WEIGHT_PAINT"
    TEXTURE_PAINT = "TEXTURE_PAINT"
    PARTICLE_EDIT = "PARTICLE_EDIT"


class ObjectAction(str, Enum):
    RENAME = "RENAME"
    CREATE = "CREATE"
    DELETE = "DELETE"
    DUPLICATE = "DUPLICATE"
    JOIN = "JOIN"
    PARENT = "PARENT"
    CLEAR_PARENT = "CLEAR_PARENT"
    SET_ORIGIN = "SET_ORIGIN"
    SELECT = "SELECT"
    TRANSFORM = "TRANSFORM"
    LIST = "LIST"
    GET_INFO = "GET_INFO"
    SET_PARENT = "SET_PARENT"
    ADD_MODIFIER = "ADD_MODIFIER"


class ObjectOrigin(str, Enum):
    GEOMETRY_ORIGIN = "GEOMETRY_ORIGIN"
    ORIGIN_GEOMETRY = "ORIGIN_GEOMETRY"
    ORIGIN_CURSOR = "ORIGIN_CURSOR"
    ORIGIN_CENTER_OF_MASS = "ORIGIN_CENTER_OF_MASS"
    ORIGIN_CENTER_OF_VOLUME = "ORIGIN_CENTER_OF_VOLUME"


class CollectionAction(str, Enum):
    CREATE = "CREATE"
    DELETE = "DELETE"
    LINK_OBJECT = "LINK_OBJECT"
    UNLINK_OBJECT = "UNLINK_OBJECT"
    LIST = "LIST"
    SET_VISIBILITY = "SET_VISIBILITY"
    CREATE_HIERARCHY = "CREATE_HIERARCHY"
    SET_COLLECTION_VISIBILITY = "SET_COLLECTION_VISIBILITY"
    SET_COLLECTION_EXCLUDE = "SET_COLLECTION_EXCLUDE"
    MOVE_TO_COLLECTION_HIERARCHY = "MOVE_TO_COLLECTION_HIERARCHY"
    CREATE_VIEW_LAYER = "CREATE_VIEW_LAYER"
    SET_VIEW_LAYER_VISIBILITY = "SET_VIEW_LAYER_VISIBILITY"
    COPY_VIEW_LAYER = "COPY_VIEW_LAYER"
    MARK_ASSET = "MARK_ASSET"
    CLEAR_ASSET = "CLEAR_ASSET"
    CREATE_ASSET = "CREATE_ASSET"
    SET_RENDER_VISIBILITY = "SET_RENDER_VISIBILITY"
    SET_HOLDOUT = "SET_HOLDOUT"
    SET_INDIRECT_ONLY = "SET_INDIRECT_ONLY"


class RenderEngine(str, Enum):
    CYCLES = "CYCLES"
    EEVEE = "BLENDER_EEVEE"  # Blender 5.0+
    EEVEE_NEXT = "BLENDER_EEVEE_NEXT"  # Blender 4.2-4.x alias (auto-falls back to EEVEE)
    WORKBENCH = "BLENDER_WORKBENCH"


class BakeAction(str, Enum):
    BAKE = "BAKE"
    SETUP_MATERIALS = "SETUP_MATERIALS"
    CREATE_IMAGE = "CREATE_IMAGE"
    CONFIGURE = "CONFIGURE"
    SETUP_BAKE_SCENE = "SETUP_BAKE_SCENE"
    PREPARE_LOW_POLY = "PREPARE_LOW_POLY"
    CREATE_BAKE_MATERIAL = "CREATE_BAKE_MATERIAL"
    BAKE_NORMAL = "BAKE_NORMAL"
    BAKE_AO = "BAKE_AO"
    BAKE_EMISSION = "BAKE_EMISSION"
    BAKE_LIGHTMAP = "BAKE_LIGHTMAP"
    BAKE_DIFFUSE = "BAKE_DIFFUSE"
    BAKE_GLOSSY = "BAKE_GLOSSY"
    BAKE_SHADOW = "BAKE_SHADOW"
    BAKE_DISPLACEMENT = "BAKE_DISPLACEMENT"
    BAKE_COMBINED = "BAKE_COMBINED"


class BMeshAction(str, Enum):
    TRANSFORM = "TRANSFORM"
    EXTRUDE = "EXTRUDE"
    INSET = "INSET"
    BEVEL = "BEVEL"
    BRIDGE = "BRIDGE"
    SUBDIVIDE = "SUBDIVIDE"
    DELETE = "DELETE"
    DUPLICATE = "DUPLICATE"
    DISSOLVE = "DISSOLVE"
    POKE = "POKE"
    FILL = "FILL"
    GRID_FILL = "GRID_FILL"
    MERGE = "MERGE"
    SPLIT = "SPLIT"
    SEPARATE = "SEPARATE"
    BISECT = "BISECT"
    ANALYZE = "ANALYZE"
    UNWRAP = "UNWRAP"
    RECALC_NORMALS = "RECALC_NORMALS"
    MERGE_BY_DISTANCE = "MERGE_BY_DISTANCE"
    SELECT_NON_MANIFOLD = "SELECT_NON_MANIFOLD"
    SLICE = "SLICE"
    SYMMETRIZE = "SYMMETRIZE"
    SPIN = "SPIN"
    SMOOTH = "SMOOTH"
    RANDOMIZE = "RANDOMIZE"


class UnityAction(str, Enum):
    OPTIMIZE_FOR_UNITY = "OPTIMIZE_FOR_UNITY"
    SETUP_PBR_MATERIALS = "SETUP_PBR_MATERIALS"
    EXPORT_FBX = "EXPORT_FBX"
    CHECK_COMPATIBILITY = "CHECK_COMPATIBILITY"
    FIX_ROTATION = "FIX_ROTATION"
    FIX_SCALE = "FIX_SCALE"
    CONVERT_TO_INSTANCES = "CONVERT_TO_INSTANCES"
    VALIDATE_HIERARCHY = "VALIDATE_HIERARCHY"


class UnityCollectionAction(str, Enum):
    CREATE_COLLECTION = "CREATE_COLLECTION"
    MOVE_TO_COLLECTION = "MOVE_TO_COLLECTION"
    LIST_COLLECTIONS = "LIST_COLLECTIONS"


class UnityObjectAction(str, Enum):
    CREATE_PRIMITIVE = "CREATE_PRIMITIVE"
    DELETE_OBJECT = "DELETE_OBJECT"
    DUPLICATE_OBJECT = "DUPLICATE_OBJECT"
    SET_TRANSFORM = "SET_TRANSFORM"
    APPLY_TRANSFORM = "APPLY_TRANSFORM"
    SET_PARENT = "SET_PARENT"
    SET_ORIGIN = "SET_ORIGIN"
    SET_VISIBILITY = "SET_VISIBILITY"
    GET_BOUNDING_BOX = "GET_BOUNDING_BOX"
    SNAP_TO = "SNAP_TO"


class MaterialAction(str, Enum):
    CREATE = "CREATE"
    ASSIGN = "ASSIGN"
    DELETE = "DELETE"
    LIST = "LIST"
    SET_PBR = "SET_PBR"
    PRESET_METALLIC = "PRESET_METALLIC"
    PRESET_GLASS = "PRESET_GLASS"
    PRESET_EMISSION = "PRESET_EMISSION"


class GeometryNodeAction(str, Enum):
    CREATE_TREE = "CREATE_TREE"
    ADD_NODE = "ADD_NODE"
    LINK_NODES = "LINK_NODES"
    SET_INPUT_VALUE = "SET_INPUT_VALUE"
    LIST_NODES = "LIST_NODES"
    DELETE_NODE = "DELETE_NODE"


class GeometryNodeAdvancedAction(str, Enum):
    CREATE_PARTICLE_SIMULATION = "CREATE_PARTICLE_SIMULATION"
    CREATE_DIFFUSION_SIMULATION = "CREATE_DIFFUSION_SIMULATION"
    CREATE_RELAXATION_ZONE = "CREATE_RELAXATION_ZONE"
    CREATE_BUNDLE_PIPELINE = "CREATE_BUNDLE_PIPELINE"
    CREATE_CLOSURE = "CREATE_CLOSURE"
    CREATE_PROCEDURAL_CITY = "CREATE_PROCEDURAL_CITY"
    CREATE_PROCEDURAL_FOREST = "CREATE_PROCEDURAL_FOREST"
    CREATE_REPEAT_ZONE = "CREATE_REPEAT_ZONE"
    CREATE_FOREACH_ZONE = "CREATE_FOREACH_ZONE"
    ADD_SIMULATION_STATE = "ADD_SIMULATION_STATE"


class PolyHavenAction(str, Enum):
    STATUS = "STATUS"
    SEARCH = "SEARCH"
    IMPORT_HDRI = "IMPORT_HDRI"
    IMPORT_MODEL = "IMPORT_MODEL"
    IMPORT_MATERIAL = "IMPORT_MATERIAL"


class AnimationAction(str, Enum):
    SET_FRAME = "SET_FRAME"
    GET_FRAME = "GET_FRAME"
    INSERT_KEYFRAME = "INSERT_KEYFRAME"
    INSERT_KEYFRAME_MULTI = "INSERT_KEYFRAME_MULTI"
    DELETE_KEYFRAME = "DELETE_KEYFRAME"
    CLEAR_KEYFRAMES = "CLEAR_KEYFRAMES"
    PLAY = "PLAY"
    STOP = "STOP"
    SET_RANGE = "SET_RANGE"
    INTENT_BASED_KEYFRAME = "INTENT_BASED_KEYFRAME"


class RiggingAction(str, Enum):
    CREATE = "CREATE"
    EXTRUDE = "EXTRUDE"
    SYMMETRIZE = "SYMMETRIZE"
    DISCONNECT = "DISCONNECT"
    TRANSFORM_BONE = "TRANSFORM_BONE"
    CONSTRAINT = "CONSTRAINT"
    GENERATE_METARIG = "GENERATE_METARIG"


class JobsAction(str, Enum):
    CHECK_STATUS = "CHECK_STATUS"
    CANCEL_JOB = "CANCEL_JOB"
    LIST_JOBS = "LIST_JOBS"


class MocapAction(str, Enum):
    IMPORT_BVH = "IMPORT_BVH"
    IMPORT_FBX_ANIMATION = "IMPORT_FBX_ANIMATION"
    IMPORT_MOTION_FOLDER = "IMPORT_MOTION_FOLDER"
    CLEAN_NOISE = "CLEAN_NOISE"
    SMOOTH_CURVES = "SMOOTH_CURVES"
    REDUCE_KEYFRAMES = "REDUCE_KEYFRAMES"
    FIX_GIMBAL_LOCK = "FIX_GIMBAL_LOCK"
    RETARGET_TO_RIG = "RETARGET_TO_RIG"
    AUTO_REMAP_BONES = "AUTO_REMAP_BONES"
    SCALE_MOTION = "SCALE_MOTION"
    MIRROR_MOTION = "MIRROR_MOTION"
    FOOT_LOCK_DETECT = "FOOT_LOCK_DETECT"
    FOOT_LOCK_FIX = "FOOT_LOCK_FIX"
    GROUND_CONTACT = "GROUND_CONTACT"
    LOOP_ANIMATION = "LOOP_ANIMATION"
    BLEND_ANIMATIONS = "BLEND_ANIMATIONS"
    CROSSFADE_POSES = "CROSSFADE_POSES"
    EXPORT_BVH = "EXPORT_BVH"
    EXPORT_FBX_ANIMATION = "EXPORT_FBX_ANIMATION"
    BAKE_TO_KEYFRAMES = "BAKE_TO_KEYFRAMES"
    ANALYZE_MOTION = "ANALYZE_MOTION"
    COMPARE_POSES = "COMPARE_POSES"
    EXTRACT_ROOT_MOTION = "EXTRACT_ROOT_MOTION"


class DriverAction(str, Enum):
    ADD_DRIVER = "ADD_DRIVER"
    REMOVE_DRIVER = "REMOVE_DRIVER"
    SET_EXPRESSION = "SET_EXPRESSION"
    SET_VARIABLE = "SET_VARIABLE"
    GET_DRIVER_INFO = "GET_DRIVER_INFO"
    LIST_DRIVERS = "LIST_DRIVERS"
    MUTE_DRIVER = "MUTE_DRIVER"
    UNMUTE_DRIVER = "UNMUTE_DRIVER"
    CREATE_FCURVE_DRIVER = "CREATE_FCURVE_DRIVER"


class ConstraintAction(str, Enum):
    ADD_CONSTRAINT = "ADD_CONSTRAINT"
    REMOVE_CONSTRAINT = "REMOVE_CONSTRAINT"
    SET_TARGET = "SET_TARGET"
    SET_INFLUENCE = "SET_INFLUENCE"
    SET_PROPERTIES = "SET_PROPERTIES"
    LIST_CONSTRAINTS = "LIST_CONSTRAINTS"
    MUTE_CONSTRAINT = "MUTE_CONSTRAINT"
    UNMUTE_CONSTRAINT = "UNMUTE_CONSTRAINT"
    COPY_TRANSFORMS = "COPY_TRANSFORMS"
    LIMIT_ROTATION = "LIMIT_ROTATION"
    LIMIT_LOCATION = "LIMIT_LOCATION"


class ConstraintType(str, Enum):
    COPY_LOCATION = "COPY_LOCATION"
    COPY_ROTATION = "COPY_ROTATION"
    COPY_SCALE = "COPY_SCALE"
    COPY_TRANSFORMS = "COPY_TRANSFORMS"
    LIMIT_DISTANCE = "LIMIT_DISTANCE"
    LIMIT_LOCATION = "LIMIT_LOCATION"
    LIMIT_ROTATION = "LIMIT_ROTATION"
    LIMIT_SCALE = "LIMIT_SCALE"
    MAINTAIN_VOLUME = "MAINTAIN_VOLUME"
    TRANSFORM = "TRANSFORM"
    TRANSFORM_CACHE = "TRANSFORM_CACHE"
    CLAMP_TO = "CLAMP_TO"
    DAMPED_TRACK = "DAMPED_TRACK"
    IK = "IK"
    LOCKED_TRACK = "LOCKED_TRACK"
    SPLINE_IK = "SPLINE_IK"
    STRETCH_TO = "STRETCH_TO"
    TRACK_TO = "TRACK_TO"
    ACTION = "ACTION"
    ARMATURE = "ARMATURE"
    CHILD_OF = "CHILD_OF"
    FLOOR = "FLOOR"
    FOLLOW_PATH = "FOLLOW_PATH"
    PIVOT = "PIVOT"
    SHRINKWRAP = "SHRINKWRAP"
    IK_SETUP = "IK_SETUP"


class SceneAction(str, Enum):
    OPEN_FILE = "OPEN_FILE"
    SAVE_FILE = "SAVE_FILE"
    NEW_SCENE = "NEW_SCENE"
    PLAYBACK_START = "PLAYBACK_START"
    PLAYBACK_STOP = "PLAYBACK_STOP"
    INSPECT_OBJECT = "INSPECT_OBJECT"
    INSPECT_SCENE = "INSPECT_SCENE"
    SET_UNIT_SYSTEM = "SET_UNIT_SYSTEM"
    CLEAN_ORPHANS = "CLEAN_ORPHANS"
    GET_3D_CURSOR = "GET_3D_CURSOR"
    SET_3D_CURSOR = "SET_3D_CURSOR"


class CameraAction(str, Enum):
    CREATE = "CREATE"
    SET_ACTIVE = "SET_ACTIVE"
    LOOK_AT = "LOOK_AT"
    SET_TRANSFORM = "SET_TRANSFORM"
    SET_LENS = "SET_LENS"
    SET_DOF = "SET_DOF"
    FRAME_OBJECT = "FRAME_OBJECT"
    LIST_CAMERAS = "LIST_CAMERAS"
    DELETE = "DELETE"
    GET_VIEWPORT_SCREENSHOT = "GET_VIEWPORT_SCREENSHOT"


class LightAction(str, Enum):
    CREATE = "CREATE"
    SET_ENERGY = "SET_ENERGY"
    SET_COLOR = "SET_COLOR"
    SET_TRANSFORM = "SET_TRANSFORM"
    SETUP_THREE_POINT = "SETUP_THREE_POINT"
    SETUP_HDRI = "SETUP_HDRI"
    SETUP_STUDIO = "SETUP_STUDIO"
    LIST_LIGHTS = "LIST_LIGHTS"
    DELETE = "DELETE"


class LightType(str, Enum):
    POINT = "POINT"
    SUN = "SUN"
    SPOT = "SPOT"
    AREA = "AREA"


class RenderAction(str, Enum):
    SET_ENGINE = "SET_ENGINE"
    SET_RESOLUTION = "SET_RESOLUTION"
    SET_SAMPLES = "SET_SAMPLES"
    RENDER_FRAME = "RENDER_FRAME"
    RENDER_STILL = "RENDER_STILL"  # Alias for RENDER_FRAME (single frame)
    RENDER_ANIMATION = "RENDER_ANIMATION"
    SET_QUALITY_PRESET = "SET_QUALITY_PRESET"


class RenderQualityPreset(str, Enum):
    DRAFT = "DRAFT"
    HD_READY = "HD_READY"
    FULL_HD = "FULL_HD"
    ULTRA_4K = "4K_ULTRA"
    PRODUCTION = "PRODUCTION"


class EeveeNextAction(str, Enum):
    SETUP_EEVEE_NEXT = "SETUP_EEVEE_NEXT"
    SETUP_RAYTRACING = "SETUP_RAYTRACING"
    OPTIMIZE_VIEWPORT = "OPTIMIZE_VIEWPORT"
    CREATE_CLAY_VIEW_LAYER = "CREATE_CLAY_VIEW_LAYER"
    CREATE_WIREFRAME_VIEW_LAYER = "CREATE_WIREFRAME_VIEW_LAYER"
    SET_VIEW_LAYER_OVERRIDE = "SET_VIEW_LAYER_OVERRIDE"
    ENABLE_RENDER_PASSES = "ENABLE_RENDER_PASSES"
    SETUP_CRYPTOMATTE = "SETUP_CRYPTOMATTE"
    SETUP_FOR_CI_CD = "SETUP_FOR_CI_CD"


class CompositingAction(str, Enum):
    ENABLE_NODES = "ENABLE_NODES"
    ADD_NODE = "ADD_NODE"
    DELETE_NODE = "DELETE_NODE"
    LINK_NODES = "LINK_NODES"
    UNLINK_NODES = "UNLINK_NODES"
    CLEAR_NODES = "CLEAR_NODES"
    LIST_NODES = "LIST_NODES"
    GET_NODE_INPUTS = "GET_NODE_INPUTS"
    GET_NODE_OUTPUTS = "GET_NODE_OUTPUTS"
    SET_INPUT_VALUE = "SET_INPUT_VALUE"
    GET_INPUT_VALUE = "GET_INPUT_VALUE"
    AUTO_LAYOUT = "AUTO_LAYOUT"
    CREATE_COMMON_SETUP = "CREATE_COMMON_SETUP"


class CompositorModifierAction(str, Enum):
    ADD_COMPOSITOR_MODIFIER = "ADD_COMPOSITOR_MODIFIER"
    ADD_EFFECT_CHAIN = "ADD_EFFECT_CHAIN"
    REMOVE_MODIFIER = "REMOVE_MODIFIER"
    ADD_VSE_STRIP = "ADD_VSE_STRIP"
    SETUP_REALTIME_COMPOSITOR = "SETUP_REALTIME_COMPOSITOR"
    ADD_VIEWPORT_EFFECT = "ADD_VIEWPORT_EFFECT"


class SequencerAction(str, Enum):
    ADD_MOVIE = "ADD_MOVIE"
    ADD_SOUND = "ADD_SOUND"
    ADD_IMAGE = "ADD_IMAGE"
    ADD_IMAGE_STRIP = "ADD_IMAGE_STRIP"
    CUT = "CUT"
    DELETE_STRIP = "DELETE_STRIP"
    SET_VOLUME = "SET_VOLUME"
    LIST_STRIPS = "LIST_STRIPS"
    GET_STRIP_INFO = "GET_STRIP_INFO"
    SET_STRIP_RANGE = "SET_STRIP_RANGE"
    SET_STRIP_OPACITY = "SET_STRIP_OPACITY"
    SET_STRIP_BLEND = "SET_STRIP_BLEND"
    MUTE_STRIP = "MUTE_STRIP"
    UNMUTE_STRIP = "UNMUTE_STRIP"
    CREATE_META_STRIP = "CREATE_META_STRIP"
    RENDER_PREVIEW = "RENDER_PREVIEW"


class SequencerBlendType(str, Enum):
    REPLACE = "REPLACE"
    CROSS = "CROSS"
    ADD = "ADD"
    SUBTRACT = "SUBTRACT"
    ALPHA_OVER = "ALPHA_OVER"
    ALPHA_UNDER = "ALPHA_UNDER"
    GAMMA_CROSS = "GAMMA_CROSS"
    MULTIPLY = "MULTIPLY"
    OVER_DROP = "OVER_DROP"


class HunyuanAction(str, Enum):
    GENERATE = "GENERATE"
    STATUS = "STATUS"
    CHECK_JOB = "CHECK_JOB"
    IMPORT = "IMPORT"


class Hyper3DAction(str, Enum):
    GENERATE = "GENERATE"
    STATUS = "STATUS"
    CHECK_JOB = "CHECK_JOB"
    IMPORT = "IMPORT"


class SketchfabAction(str, Enum):
    STATUS = "STATUS"
    SEARCH = "SEARCH"
    GET_DOWNLOAD_URL = "GET_DOWNLOAD_URL"
    IMPORT = "IMPORT"


class AdvancedBatchAction(str, Enum):
    ARRAY_WITH_VARIATION = "ARRAY_WITH_VARIATION"
    AUTOMATION_MACRO = "AUTOMATION_MACRO"
    BAKE_ALL_DYNAMICS = "BAKE_ALL_DYNAMICS"
    CHAIN_OPERATIONS = "CHAIN_OPERATIONS"
    CONDITIONAL_BATCH = "CONDITIONAL_BATCH"
    DISTRIBUTE_ALONG_CURVE = "DISTRIBUTE_ALONG_CURVE"
    EXPORT_BATCH_VARIANTS = "EXPORT_BATCH_VARIANTS"
    FILTER_AND_PROCESS = "FILTER_AND_PROCESS"
    INSTANCER_SYSTEM = "INSTANCER_SYSTEM"
    PIPELINE_EXECUTE = "PIPELINE_EXECUTE"
    SCATTER_OBJECTS = "SCATTER_OBJECTS"


class AnimationAdvancedAction(str, Enum):
    ANIMATION_EXPORT_GAME = "ANIMATION_EXPORT_GAME"
    ANIMATION_EXPORT_UNITY = "ANIMATION_EXPORT_UNITY"
    ANIMATION_EXPORT_UNREAL = "ANIMATION_EXPORT_UNREAL"
    ANIMATION_LAYER_ADD = "ANIMATION_LAYER_ADD"
    ANIMATION_LAYER_MERGE = "ANIMATION_LAYER_MERGE"
    ANIMATION_LAYER_MIX = "ANIMATION_LAYER_MIX"
    BREATHING_ANIMATION = "BREATHING_ANIMATION"
    CURVE_AMPLIFY = "CURVE_AMPLIFY"
    CURVE_EULER_FILTER = "CURVE_EULER_FILTER"
    CURVE_FLATTEN = "CURVE_FLATTEN"
    CURVE_NOISE = "CURVE_NOISE"
    CURVE_RETIME = "CURVE_RETIME"
    CURVE_SMOOTH = "CURVE_SMOOTH"
    FOLLOW_PATH_SETUP = "FOLLOW_PATH_SETUP"
    HEAD_TURN_GENERATE = "HEAD_TURN_GENERATE"
    IDLE_POSE_GENERATE = "IDLE_POSE_GENERATE"
    IK_FK_SNAP = "IK_FK_SNAP"
    IK_FK_SWITCH = "IK_FK_SWITCH"
    LOOK_AT_SETUP = "LOOK_AT_SETUP"
    MOTION_PATH_CALCULATE = "MOTION_PATH_CALCULATE"
    MOTION_PATH_CLEAR = "MOTION_PATH_CLEAR"
    MOTION_PATH_VISUALIZE = "MOTION_PATH_VISUALIZE"
    POSE_BLEND = "POSE_BLEND"
    POSE_DELETE = "POSE_DELETE"
    POSE_LIBRARY_CREATE = "POSE_LIBRARY_CREATE"
    POSE_LOAD = "POSE_LOAD"
    POSE_MIRROR = "POSE_MIRROR"
    POSE_SAVE = "POSE_SAVE"
    REVERSE_ANIMATION = "REVERSE_ANIMATION"
    RUN_CYCLE_GENERATE = "RUN_CYCLE_GENERATE"
    SLOW_DOWN = "SLOW_DOWN"
    SPEED_UP = "SPEED_UP"
    TAIL_WAG_GENERATE = "TAIL_WAG_GENERATE"
    TIME_REMAP = "TIME_REMAP"
    WALK_CYCLE_GENERATE = "WALK_CYCLE_GENERATE"

    # AAA Studio Integrations
    BAKE_PHYSICS_TO_ACTION = "BAKE_PHYSICS_TO_ACTION"
    GENERATE_LIPSYNC = "GENERATE_LIPSYNC"


class AnimationSlotsAction(str, Enum):
    ADD_CYCLES_MODIFIER = "ADD_CYCLES_MODIFIER"
    ADD_DRIVER = "ADD_DRIVER"
    ADD_LIMITS_MODIFIER = "ADD_LIMITS_MODIFIER"
    ADD_NLA_STRIP = "ADD_NLA_STRIP"
    ADD_NOISE_MODIFIER = "ADD_NOISE_MODIFIER"
    ASSIGN_SLOT = "ASSIGN_SLOT"
    BAKE_ANIMATION = "BAKE_ANIMATION"
    BAKE_CONSTRAINTS = "BAKE_CONSTRAINTS"
    COPY_KEYFRAME_RANGE = "COPY_KEYFRAME_RANGE"
    CREATE_ACTION_SLOTS = "CREATE_ACTION_SLOTS"
    CREATE_NLA_TRACK = "CREATE_NLA_TRACK"
    INSERT_KEYFRAME = "INSERT_KEYFRAME"
    INSERT_KEYFRAME_INTERPOLATED = "INSERT_KEYFRAME_INTERPOLATED"
    SET_STRIP_INFLUENCE = "SET_STRIP_INFLUENCE"


class BatchAction(str, Enum):
    ADD_MODIFIER = "ADD_MODIFIER"
    APPLY_MODIFIERS = "APPLY_MODIFIERS"
    APPLY_SCALE = "APPLY_SCALE"
    ASSIGN = "ASSIGN"
    CLEAR_MATERIALS = "CLEAR_MATERIALS"
    CLONE = "CLONE"
    COPY = "COPY"
    DECIMATE = "DECIMATE"
    DELETE = "DELETE"
    DUPLICATE = "DUPLICATE"
    JOIN_MESHES = "JOIN_MESHES"
    MAKE_INSTANCES_REAL = "MAKE_INSTANCES_REAL"
    ORIGIN_TO_GEOMETRY = "ORIGIN_TO_GEOMETRY"
    PARENT_TO_EMPTY = "PARENT_TO_EMPTY"
    REMOVE_MODIFIERS = "REMOVE_MODIFIERS"
    RENAME = "RENAME"
    SELECT_BY_NAME = "SELECT_BY_NAME"
    SELECT_BY_TYPE = "SELECT_BY_TYPE"
    SET_MATERIAL = "SET_MATERIAL"
    SET_VISIBILITY = "SET_VISIBILITY"
    SMART_UV_UNWRAP = "SMART_UV_UNWRAP"
    TRIANGULATE = "TRIANGULATE"


class CloudRenderAction(str, Enum):
    CALCULATE_RENDER_TIME = "CALCULATE_RENDER_TIME"
    OPTIMIZE_FOR_FARM = "OPTIMIZE_FOR_FARM"
    PACKAGE_ASSETS = "PACKAGE_ASSETS"
    VALIDATE_SCENE = "VALIDATE_SCENE"


class ExportAction(str, Enum):
    EXPORT_GLTF = "EXPORT_GLTF"
    EXPORT_FBX = "EXPORT_FBX"
    EXPORT_OBJ = "EXPORT_OBJ"


class ExportPipelineAction(str, Enum):
    CHECK_EXPORT_PATH = "CHECK_EXPORT_PATH"
    EXPORT_ALEMBIC = "EXPORT_ALEMBIC"
    EXPORT_ALL_FORMATS = "EXPORT_ALL_FORMATS"
    EXPORT_FBX = "EXPORT_FBX"
    EXPORT_GLTF = "EXPORT_GLTF"
    EXPORT_GLTF_DRACO = "EXPORT_GLTF_DRACO"
    EXPORT_OBJ = "EXPORT_OBJ"
    EXPORT_USD = "EXPORT_USD"
    EXPORT_GAMEDEV_READY = "EXPORT_GAMEDEV_READY"
    VALIDATE_FOR_EXPORT = "VALIDATE_FOR_EXPORT"
    VALIDATE_GLTF = "VALIDATE_GLTF"


class HeadlessModeAction(str, Enum):
    AUTO_PURGE = "AUTO_PURGE"
    DETECT_MODE = "DETECT_MODE"
    ENSURE_CONTEXT = "ENSURE_CONTEXT"
    GET_MEMORY_STATS = "GET_MEMORY_STATS"
    PURGE_MEMORY = "PURGE_MEMORY"
    RENDER_HEADLESS = "RENDER_HEADLESS"
    SETUP_CI_CD = "SETUP_CI_CD"
    VALIDATE_SCENE = "VALIDATE_SCENE"


class ModelingAction(str, Enum):
    ADD_MODIFIER = "ADD_MODIFIER"
    ADD_PRIMITIVE = "ADD_PRIMITIVE"
    ALIGN_TO_TARGET = "ALIGN_TO_TARGET"
    APPLY_MODIFIER = "APPLY_MODIFIER"
    APPLY_PRESET = "APPLY_PRESET"
    COMMIT = "COMMIT"
    EDIT_MESH = "EDIT_MESH"
    PLACE_RELATIVE_TO = "PLACE_RELATIVE_TO"
    PRECISE_PLACEMENT = "PRECISE_PLACEMENT"
    PREVIEW = "PREVIEW"
    QUERY_SEMANTIC = "QUERY_SEMANTIC"
    SET_OFFSET = "SET_OFFSET"
    TAG_OBJECT = "TAG_OBJECT"
    VALIDATE = "VALIDATE"


class PhysicsAction(str, Enum):
    ALL_BAKE = "ALL_BAKE"
    ALL_CACHE_CLEAR = "ALL_CACHE_CLEAR"
    CLOTH_BAKE = "CLOTH_BAKE"
    CLOTH_CACHE_CLEAR = "CLOTH_CACHE_CLEAR"
    CLOTH_PIN = "CLOTH_PIN"
    CLOTH_PRESET = "CLOTH_PRESET"
    CLOTH_SIM_SETUP = "CLOTH_SIM_SETUP"
    CLOTH_UNPIN = "CLOTH_UNPIN"
    COLLISION_SETUP = "COLLISION_SETUP"
    FLUID_ADD_EFFECTOR = "FLUID_ADD_EFFECTOR"
    FLUID_ADD_FLOW = "FLUID_ADD_FLOW"
    FLUID_BAKE = "FLUID_BAKE"
    FLUID_CACHE_CLEAR = "FLUID_CACHE_CLEAR"
    FLUID_DOMAIN_SETUP = "FLUID_DOMAIN_SETUP"
    FORCE_FIELD_ADD = "FORCE_FIELD_ADD"
    FORCE_FIELD_CONFIGURE = "FORCE_FIELD_CONFIGURE"
    FORCE_FIELD_REMOVE = "FORCE_FIELD_REMOVE"
    PARTICLE_BAKE = "PARTICLE_BAKE"
    PARTICLE_EMISSION = "PARTICLE_EMISSION"
    PARTICLE_EXPLOSION = "PARTICLE_EXPLOSION"
    PARTICLE_FUR = "PARTICLE_FUR"
    PARTICLE_HAIR = "PARTICLE_HAIR"
    RIGID_BODY_ADD = "RIGID_BODY_ADD"
    RIGID_BODY_BAKE = "RIGID_BODY_BAKE"
    RIGID_BODY_CACHE_CLEAR = "RIGID_BODY_CACHE_CLEAR"
    RIGID_BODY_REMOVE = "RIGID_BODY_REMOVE"
    RIGID_BODY_WORLD_SETUP = "RIGID_BODY_WORLD_SETUP"
    SIMULATION_PLAY = "SIMULATION_PLAY"
    SIMULATION_STOP = "SIMULATION_STOP"
    SOFT_BODY_BAKE = "SOFT_BODY_BAKE"
    SOFT_BODY_SETUP = "SOFT_BODY_SETUP"


class ProceduralAction(str, Enum):
    CHAIN_MAIL = "CHAIN_MAIL"
    CITY_LAYOUT = "CITY_LAYOUT"
    CRYSTAL_GENERATE = "CRYSTAL_GENERATE"
    FABRIC_WEAVE = "FABRIC_WEAVE"
    FRACTAL_GENERATE = "FRACTAL_GENERATE"
    GEOMETRIC_PATTERN = "GEOMETRIC_PATTERN"
    L_SYSTEM_PLANT = "L_SYSTEM_PLANT"
    MAZE_GENERATE = "MAZE_GENERATE"
    PARAMETRIC_CURVE = "PARAMETRIC_CURVE"
    PARTICLE_FLOWER = "PARTICLE_FLOWER"
    ROCK_GENERATE = "ROCK_GENERATE"
    SPIRAL_GALAXY = "SPIRAL_GALAXY"
    TERRAIN_GENERATE = "TERRAIN_GENERATE"
    TREE_GENERATE = "TREE_GENERATE"
    VORONOI_PATTERN = "VORONOI_PATTERN"


class ProfilingAction(str, Enum):
    ANALYZE_VIEWPORT = "ANALYZE_VIEWPORT"
    COMPARE_OBJECTS = "COMPARE_OBJECTS"
    FIND_DUPLICATE_MESHES = "FIND_DUPLICATE_MESHES"
    FIND_HEAVY_OBJECTS = "FIND_HEAVY_OBJECTS"
    FIND_UNUSED_DATA = "FIND_UNUSED_DATA"
    MATERIAL_ANALYSIS = "MATERIAL_ANALYSIS"
    MEMORY_USAGE = "MEMORY_USAGE"
    MESH_ANALYSIS = "MESH_ANALYSIS"
    OPTIMIZATION_REPORT = "OPTIMIZATION_REPORT"
    RENDER_STATS = "RENDER_STATS"
    SCENE_STATS = "SCENE_STATS"
    TEXTURE_ANALYSIS = "TEXTURE_ANALYSIS"


class RenderOptimizationAction(str, Enum):
    ADAPTIVE_SAMPLING_DISABLE = "ADAPTIVE_SAMPLING_DISABLE"
    ADAPTIVE_SAMPLING_ENABLE = "ADAPTIVE_SAMPLING_ENABLE"
    ADAPTIVE_SUBDIVISION_SETUP = "ADAPTIVE_SUBDIVISION_SETUP"
    BAKE_IRRADIANCE = "BAKE_IRRADIANCE"
    DENOISE_DISABLE = "DENOISE_DISABLE"
    DENOISE_ENABLE = "DENOISE_ENABLE"
    DENOISE_SETUP = "DENOISE_SETUP"
    GPU_MEMORY_OPTIMIZE = "GPU_MEMORY_OPTIMIZE"
    LIGHT_TREE_BUILD = "LIGHT_TREE_BUILD"
    LIGHT_TREE_ENABLE = "LIGHT_TREE_ENABLE"
    OPTIMIZE_FOR_ANIMATION = "OPTIMIZE_FOR_ANIMATION"
    OPTIMIZE_FOR_STILL = "OPTIMIZE_FOR_STILL"
    OPTIMIZE_SAMPLES = "OPTIMIZE_SAMPLES"
    PERSISTENT_DATA_ENABLE = "PERSISTENT_DATA_ENABLE"
    RENDER_REGION_AUTO = "RENDER_REGION_AUTO"
    RENDER_REGION_SET = "RENDER_REGION_SET"
    RESOLUTION_SCALE = "RESOLUTION_SCALE"
    SAMPLE_OPTIMIZATION_REPORT = "SAMPLE_OPTIMIZATION_REPORT"
    TILE_SIZE_OPTIMIZE = "TILE_SIZE_OPTIMIZE"


class ScriptingAction(str, Enum):
    CREATE_TEXT_BLOCK = "CREATE_TEXT_BLOCK"
    EXECUTE_CODE = "EXECUTE_CODE"
    EXECUTE_TEXT_BLOCK = "EXECUTE_TEXT_BLOCK"


class SimulationPresetAction(str, Enum):
    PRESET_BUBBLES = "PRESET_BUBBLES"
    PRESET_CHAIN_REACTION = "PRESET_CHAIN_REACTION"
    PRESET_CONFETTI = "PRESET_CONFETTI"
    PRESET_DESTRUCTION = "PRESET_DESTRUCTION"
    PRESET_EXPLOSION = "PRESET_EXPLOSION"
    PRESET_FABRIC_DRAPE = "PRESET_FABRIC_DRAPE"
    PRESET_FLAG_WIND = "PRESET_FLAG_WIND"
    PRESET_FOUNTAIN = "PRESET_FOUNTAIN"
    PRESET_RAIN = "PRESET_RAIN"
    PRESET_SMOKE_FIRE = "PRESET_SMOKE_FIRE"
    PRESET_SNOW_FALL = "PRESET_SNOW_FALL"
    PRESET_SPARKS = "PRESET_SPARKS"
    PRESET_TORNADO = "PRESET_TORNADO"
    PRESET_WAVE_POOL = "PRESET_WAVE_POOL"


class ToolGroupsAction(str, Enum):
    GET_GROUP = "GET_GROUP"
    GET_WORKFLOW = "GET_WORKFLOW"
    LIST_GROUPS = "LIST_GROUPS"
    SUGGEST_GROUP = "SUGGEST_GROUP"


class UVAction(str, Enum):
    AVERAGE_ISLANDS_SCALE = "AVERAGE_ISLANDS_SCALE"
    CUBE_PROJECT = "CUBE_PROJECT"
    CYLINDER_PROJECT = "CYLINDER_PROJECT"
    EXPORT_UV_LAYOUT = "EXPORT_UV_LAYOUT"
    LIGHTMAP_PACK = "LIGHTMAP_PACK"
    MINIMUM_STRETCH = "MINIMUM_STRETCH"
    PACK_ISLANDS = "PACK_ISLANDS"
    SEAMS_FROM_ISLANDS = "SEAMS_FROM_ISLANDS"
    SELECT_BORDER = "SELECT_BORDER"
    SELECT_PINNED = "SELECT_PINNED"
    SMART_PROJECT = "SMART_PROJECT"
    SPHERE_PROJECT = "SPHERE_PROJECT"
    STITCH = "STITCH"
    UNWRAP = "UNWRAP"
    WELD = "WELD"


class UVAdvancedAction(str, Enum):
    OVERLAP_FIX = "OVERLAP_FIX"
    PACK_UDIMS = "PACK_UDIMS"
    RECTANGLE_PACK = "RECTANGLE_PACK"
    SEAM_BY_ANGLE = "SEAM_BY_ANGLE"
    SEAM_BY_SHARP = "SEAM_BY_SHARP"
    STRAIGHTEN_ISLANDS = "STRAIGHTEN_ISLANDS"
    STRETCH_DETECT = "STRETCH_DETECT"
    TEXEL_DENSITY_CALCULATE = "TEXEL_DENSITY_CALCULATE"
    TEXEL_DENSITY_MATCH = "TEXEL_DENSITY_MATCH"
    TEXEL_DENSITY_SET = "TEXEL_DENSITY_SET"
    UDIM_ADD_TILE = "UDIM_ADD_TILE"
    UDIM_SETUP = "UDIM_SETUP"


class UVsAction(str, Enum):
    ADD_SEAM = "ADD_SEAM"
    CLEAR_SEAM = "CLEAR_SEAM"
    EXPORT_LAYOUT = "EXPORT_LAYOUT"
    LIST_CHANNELS = "LIST_CHANNELS"
    NEW_CHANNEL = "NEW_CHANNEL"
    PACK = "PACK"
    TRANSFORM = "TRANSFORM"
    UNWRAP = "UNWRAP"


class SculptAction(str, Enum):
    DISABLE_DYNTOPO = "DISABLE_DYNTOPO"
    ENABLE_DYNTOPO = "ENABLE_DYNTOPO"
    ENTER_MODE = "ENTER_MODE"
    EXIT_MODE = "EXIT_MODE"
    GET_AVAILABLE_BRUSHES = "GET_AVAILABLE_BRUSHES"
    GET_BRUSH_INFO = "GET_BRUSH_INFO"
    MASK = "MASK"
    REMESH = "REMESH"
    RESET_BRUSH = "RESET_BRUSH"
    SET_BRUSH = "SET_BRUSH"
    SET_BRUSH_SETTINGS = "SET_BRUSH_SETTINGS"
    STROKE = "STROKE"
    SYMMETRY = "SYMMETRY"


class AIToolsAction(str, Enum):
    AI_MATERIAL_SUGGEST = "AI_MATERIAL_SUGGEST"
    AUTO_COLLIDER = "AUTO_COLLIDER"
    AUTO_LOD_GENERATE = "AUTO_LOD_GENERATE"
    AUTO_RETOPOLOGY = "AUTO_RETOPOLOGY"
    AUTO_RIG_SUGGEST = "AUTO_RIG_SUGGEST"
    CONFIDENCE_AI_MATERIAL_SUGGEST = "CONFIDENCE_AI_MATERIAL_SUGGEST"
    CONFIDENCE_AUTO_LOD_GENERATE = "CONFIDENCE_AUTO_LOD_GENERATE"
    CONFIDENCE_AUTO_RETOPOLOGY = "CONFIDENCE_AUTO_RETOPOLOGY"
    CONFIDENCE_AUTO_RIG_SUGGEST = "CONFIDENCE_AUTO_RIG_SUGGEST"
    CONFIDENCE_SMART_DECIMATE = "CONFIDENCE_SMART_DECIMATE"
    CONFIDENCE_SMART_LIGHTING = "CONFIDENCE_SMART_LIGHTING"
    CONFIDENCE_SMART_UV_UNWRAP = "CONFIDENCE_SMART_UV_UNWRAP"
    DRY_RUN_AUTO_LOD_GENERATE = "DRY_RUN_AUTO_LOD_GENERATE"
    DRY_RUN_AUTO_RETOPOLOGY = "DRY_RUN_AUTO_RETOPOLOGY"
    DRY_RUN_SMART_DECIMATE = "DRY_RUN_SMART_DECIMATE"
    DRY_RUN_SMART_LIGHTING = "DRY_RUN_SMART_LIGHTING"
    DRY_RUN_SMART_UV_UNWRAP = "DRY_RUN_SMART_UV_UNWRAP"
    EXPLAIN_AI_MATERIAL_SUGGEST = "EXPLAIN_AI_MATERIAL_SUGGEST"
    EXPLAIN_AUTO_LOD_GENERATE = "EXPLAIN_AUTO_LOD_GENERATE"
    EXPLAIN_AUTO_RETOPOLOGY = "EXPLAIN_AUTO_RETOPOLOGY"
    EXPLAIN_AUTO_RIG_SUGGEST = "EXPLAIN_AUTO_RIG_SUGGEST"
    EXPLAIN_SMART_DECIMATE = "EXPLAIN_SMART_DECIMATE"
    EXPLAIN_SMART_LIGHTING = "EXPLAIN_SMART_LIGHTING"
    EXPLAIN_SMART_UV_UNWRAP = "EXPLAIN_SMART_UV_UNWRAP"
    INTELLIGENT_MERGE = "INTELLIGENT_MERGE"
    SMART_BEVEL = "SMART_BEVEL"
    SMART_CLEANUP = "SMART_CLEANUP"
    SMART_DECIMATE = "SMART_DECIMATE"
    SMART_LIGHTING = "SMART_LIGHTING"
    SMART_UV_UNWRAP = "SMART_UV_UNWRAP"


class AgentContextAction(str, Enum):
    GET_TOOL_CATALOG = "GET_TOOL_CATALOG"
    SEARCH_TOOLS = "SEARCH_TOOLS"
    GET_ACTION_HELP = "GET_ACTION_HELP"
    GET_PRIMER = "GET_PRIMER"
    GET_TACTICS = "GET_TACTICS"


class SceneComprehensionAction(str, Enum):
    CHECK_INTERSECTION = "CHECK_INTERSECTION"
    GET_SPATIAL_REPORT = "GET_SPATIAL_REPORT"
    VERIFY_ASSEMBLY = "VERIFY_ASSEMBLY"
    GET_SCENE_MATRIX = "GET_SCENE_MATRIX"
    CAST_RAY = "CAST_RAY"
    GET_OBJECTS_FLAT = "GET_OBJECTS_FLAT"
    ANALYZE_ASSEMBLY = "ANALYZE_ASSEMBLY"
    DETECT_GEOMETRY_ERRORS = "DETECT_GEOMETRY_ERRORS"
    GEOMETRY_COMPLEXITY = "GEOMETRY_COMPLEXITY"
    CHECK_PRODUCTION_READINESS = "CHECK_PRODUCTION_READINESS"
    GET_HIERARCHY_TREE = "GET_HIERARCHY_TREE"
